### ISSUE TITLE
Additonal Columns

### ISSUE THREAD

**Issue by jgeller112** [npm27/lrd#1]
First off, loving the packing! I know this can be done in Shiny, but when using the functions in R, I don't think there is an argument to include additional columns.

**Comment by npm27** [comment]
Thanks for the feedback! At the moment there isn't an argument for this when using the functions in R, but we're currently in the process of overhauling this package and that's one of many things that's being addressed. Stay tuned for updates!

**Comment by doomlab** [comment]
@jgeller112 - we did a lot of updates this - do you want to check out the additional column features? I added examples to each function, but if you have a specific one in mind, I can share a reprex.

**Comment by jgeller112** [comment]
Works perfectly! Thank you!
